//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idaho.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idaho.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control cannot be created because HttpContext is null.
        /// </summary>
        internal static string Error_NullControlContext {
            get {
                return ResourceManager.GetString("Error_NullControlContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner position must be specified before extensions.
        /// </summary>
        internal static string Error_NullCornerPosition {
            get {
                return ResourceManager.GetString("Error_NullCornerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (objectClass=computer).
        /// </summary>
        internal static string LDAP_Computer {
            get {
                return ResourceManager.GetString("LDAP_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=computer)(objectGUID={0})).
        /// </summary>
        internal static string LDAP_ComputerID {
            get {
                return ResourceManager.GetString("LDAP_ComputerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=computer)(cn={0})).
        /// </summary>
        internal static string LDAP_ComputerName {
            get {
                return ResourceManager.GetString("LDAP_ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=computer)(|{0})).
        /// </summary>
        internal static string LDAP_ComputerNames {
            get {
                return ResourceManager.GetString("LDAP_ComputerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=computer)(cn=*{0}*)).
        /// </summary>
        internal static string LDAP_ComputerTag {
            get {
                return ResourceManager.GetString("LDAP_ComputerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=computer)(cn={0})({1})).
        /// </summary>
        internal static string LDAP_ComputerTagAndUsers {
            get {
                return ResourceManager.GetString("LDAP_ComputerTagAndUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=group)(cn={0})).
        /// </summary>
        internal static string LDAP_GroupName {
            get {
                return ResourceManager.GetString("LDAP_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (objectClass=group).
        /// </summary>
        internal static string LDAP_Groups {
            get {
                return ResourceManager.GetString("LDAP_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=user)(memberOf=CN={0})).
        /// </summary>
        internal static string LDAP_GroupUsers {
            get {
                return ResourceManager.GetString("LDAP_GroupUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (objectClass=printQueue).
        /// </summary>
        internal static string LDAP_Printer {
            get {
                return ResourceManager.GetString("LDAP_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=computer)(description={0}*)).
        /// </summary>
        internal static string LDAP_UserComputer {
            get {
                return ResourceManager.GetString("LDAP_UserComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=user)(objectGUID={0})).
        /// </summary>
        internal static string LDAP_UserID {
            get {
                return ResourceManager.GetString("LDAP_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=user)(|(sAMAccountName={0})(homeDirectory=*{0}))).
        /// </summary>
        internal static string LDAP_UserLogin {
            get {
                return ResourceManager.GetString("LDAP_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=user)(cn={0})).
        /// </summary>
        internal static string LDAP_UserName {
            get {
                return ResourceManager.GetString("LDAP_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectCategory=person)(|(givenName={0}*)(sn={0}*))).
        /// </summary>
        internal static string LDAP_UserNameStartsWith {
            get {
                return ResourceManager.GetString("LDAP_UserNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectClass=organizationalUnit)(ou=Users)).
        /// </summary>
        internal static string LDAP_UserOrganizations {
            get {
                return ResourceManager.GetString("LDAP_UserOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(objectCategory=person)(objectClass=user)(!(description=Built-in account*))).
        /// </summary>
        internal static string LDAP_Users {
            get {
                return ResourceManager.GetString("LDAP_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        internal static string Number_Eight {
            get {
                return ResourceManager.GetString("Number_Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleven.
        /// </summary>
        internal static string Number_Eleven {
            get {
                return ResourceManager.GetString("Number_Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteen.
        /// </summary>
        internal static string Number_Fifteen {
            get {
                return ResourceManager.GetString("Number_Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        internal static string Number_Five {
            get {
                return ResourceManager.GetString("Number_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        internal static string Number_Four {
            get {
                return ResourceManager.GetString("Number_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourteen.
        /// </summary>
        internal static string Number_Fourteen {
            get {
                return ResourceManager.GetString("Number_Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        internal static string Number_Nine {
            get {
                return ResourceManager.GetString("Number_Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string Number_One {
            get {
                return ResourceManager.GetString("Number_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        internal static string Number_Seven {
            get {
                return ResourceManager.GetString("Number_Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        internal static string Number_Six {
            get {
                return ResourceManager.GetString("Number_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        internal static string Number_Ten {
            get {
                return ResourceManager.GetString("Number_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirteen.
        /// </summary>
        internal static string Number_Thirteen {
            get {
                return ResourceManager.GetString("Number_Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string Number_Three {
            get {
                return ResourceManager.GetString("Number_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve.
        /// </summary>
        internal static string Number_Twelve {
            get {
                return ResourceManager.GetString("Number_Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string Number_Two {
            get {
                return ResourceManager.GetString("Number_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        internal static string Number_Zero {
            get {
                return ResourceManager.GetString("Number_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\w{8}\-\w{4}\-\w{4}\-\w{4}\-\w{12}$.
        /// </summary>
        internal static string RegEx_GUID {
            get {
                return ResourceManager.GetString("RegEx_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \#{0,1}[0-9A-F]{3,6}.
        /// </summary>
        internal static string RegEx_HexColor {
            get {
                return ResourceManager.GetString("RegEx_HexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^&lt;.+&gt;([^&lt;]+)&lt;/.+&gt;.
        /// </summary>
        internal static string RegEx_HtmlTagContent {
            get {
                return ResourceManager.GetString("RegEx_HtmlTagContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://.*.
        /// </summary>
        internal static string RegEx_LDAP {
            get {
                return ResourceManager.GetString("RegEx_LDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^CN=([^,]+),OU=(Users|Test).
        /// </summary>
        internal static string RegEx_LdapGroupMember {
            get {
                return ResourceManager.GetString("RegEx_LdapGroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\\\\\w{3,10}\\[\w\\]{3,})\b.
        /// </summary>
        internal static string RegEx_NetworkPath {
            get {
                return ResourceManager.GetString("RegEx_NetworkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;\/?\w+&gt;|\&amp;\#?\w{1,10}\;|\%\d{2,3}.
        /// </summary>
        internal static string RegEx_SafeHtml {
            get {
                return ResourceManager.GetString("RegEx_SafeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b(insert|update|select|where|from|delete|in|between|values|into|and)\s+.
        /// </summary>
        internal static string RegEx_SqlKeyWords {
            get {
                return ResourceManager.GetString("RegEx_SqlKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b(insert|update|select|where|from|delete)\b.
        /// </summary>
        internal static string RegEx_SqlNewLineWords {
            get {
                return ResourceManager.GetString("RegEx_SqlNewLineWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([\s,])(&apos;[^&apos;]*&apos;)([\s,]).
        /// </summary>
        internal static string RegEx_SqlStrings {
            get {
                return ResourceManager.GetString("RegEx_SqlStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{3}\-\d{2}\-\d{4}$.
        /// </summary>
        internal static string RegEx_SSN {
            get {
                return ResourceManager.GetString("RegEx_SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button(this, {0});.
        /// </summary>
        internal static string Script_ButtonMouseOver {
            get {
                return ResourceManager.GetString("Script_ButtonMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Validation.Field(&quot;{0}&quot;,&quot;{1}&quot;,&quot;{2}&quot;,{3}).
        /// </summary>
        internal static string Script_CreateValidation {
            get {
                return ResourceManager.GetString("Script_CreateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.forms[0].{0}.focus();.
        /// </summary>
        internal static string Script_Focus {
            get {
                return ResourceManager.GetString("Script_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.SetAction({0}).
        /// </summary>
        internal static string Script_FormAction {
            get {
                return ResourceManager.GetString("Script_FormAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterPageLoad(function() {{ Page.AddClickKey(&quot;{0}&quot;, {1}); }});.
        /// </summary>
        internal static string Script_KeyForButton {
            get {
                return ResourceManager.GetString("Script_KeyForButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.OnKeyPress({0}, {1}).
        /// </summary>
        internal static string Script_KeyPressFunction {
            get {
                return ResourceManager.GetString("Script_KeyPressFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM.ListTransfer(&apos;{0}&apos;,&apos;{1}&apos;).
        /// </summary>
        internal static string Script_ListTransfer {
            get {
                return ResourceManager.GetString("Script_ListTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.Post({0}).
        /// </summary>
        internal static string Script_PostAction {
            get {
                return ResourceManager.GetString("Script_PostAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.Redirect(&apos;{0}&apos;, null, {1}).
        /// </summary>
        internal static string Script_Redirect {
            get {
                return ResourceManager.GetString("Script_Redirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM.SelectList(&apos;{0}&apos;).
        /// </summary>
        internal static string Script_SelectList {
            get {
                return ResourceManager.GetString("Script_SelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM.SetValue(&apos;id&apos;, &apos;{0}&apos;).
        /// </summary>
        internal static string Script_SetHiddenID {
            get {
                return ResourceManager.GetString("Script_SetHiddenID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM.SetValue(&apos;{0}&apos;, &apos;{1}&apos;, true).
        /// </summary>
        internal static string Script_SetNodeValue {
            get {
                return ResourceManager.GetString("Script_SetNodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.ShowDialog(&apos;{0}&apos;, {1}).
        /// </summary>
        internal static string Script_ShowDialog {
            get {
                return ResourceManager.GetString("Script_ShowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Select_Any {
            get {
                return ResourceManager.GetString("Select_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one.
        /// </summary>
        internal static string Select_Choose {
            get {
                return ResourceManager.GetString("Select_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string Select_New {
            get {
                return ResourceManager.GetString("Select_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Select_None {
            get {
                return ResourceManager.GetString("Select_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.google.com/maps?q={0} {1}.
        /// </summary>
        internal static string URL_GoogleMap {
            get {
                return ResourceManager.GetString("URL_GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/cache.ashx?key={0}&amp;type={1}.
        /// </summary>
        internal static string URL_ImageCache {
            get {
                return ResourceManager.GetString("URL_ImageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dnsstuff.com/tools/whois.ch?ip={0}.
        /// </summary>
        internal static string URL_LookupIp {
            get {
                return ResourceManager.GetString("URL_LookupIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dexknows.whitepages.com/search/ReversePhone?phone={0}{1}.
        /// </summary>
        internal static string URL_LookupPhoneNumber {
            get {
                return ResourceManager.GetString("URL_LookupPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/downloads/details.aspx?DisplayLang=en&amp;FamilyID=d88e4542-b174-4198-ae31-6884e9edd524.
        /// </summary>
        internal static string URL_VisioViewer {
            get {
                return ResourceManager.GetString("URL_VisioViewer", resourceCulture);
            }
        }
    }
}
